//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kullaniciID { get; set; }
        public string adSoyad { get; set; }
        public string mailAdresi { get; set; }
        public string sifre { get; set; }
        public string tc { get; set; }
        public string adres { get; set; }
        public string tel { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public Nullable<System.DateTime> kayitTarihi { get; set; }
    }
}
