//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stoktakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis
    {
        public int satis_id { get; set; }
        public int urun { get; set; }
        public int musteri { get; set; }
        public int adet { get; set; }
        public double fiyat { get; set; }
    
        public virtual musteriler musteriler { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
